package theme

import androidx.compose.ui.graphics.Color

// light colors
val primaryLight = Color(0xFF755B00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFAC937)
val onPrimaryContainerLight = Color(0xFF4B3A00)
val secondaryLight = Color(0xFF705C27)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFE4A4)
val onSecondaryContainerLight = Color(0xFF5A4814)
val tertiaryLight = Color(0xFF4E6700)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBBDD63)
val onTertiaryContainerLight = Color(0xFF314200)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F1)
val onBackgroundLight = Color(0xFF1F1B12)
val surfaceLight = Color(0xFFFFF8F1)
val onSurfaceLight = Color(0xFF1F1B12)
val surfaceVariantLight = Color(0xFFEEE1C8)
val onSurfaceVariantLight = Color(0xFF4E4634)
val outlineLight = Color(0xFF807661)
val outlineVariantLight = Color(0xFFD1C5AD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF353026)
val inverseOnSurfaceLight = Color(0xFFF9F0E0)
val inversePrimaryLight = Color(0xFFF0C02E)
val surfaceDimLight = Color(0xFFE2D9CA)
val surfaceBrightLight = Color(0xFFFFF8F1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFCF2E3)
val surfaceContainerLight = Color(0xFFF6EDDD)
val surfaceContainerHighLight = Color(0xFFF1E7D7)
val surfaceContainerHighestLight = Color(0xFFEBE1D2)

// dark colors
val primaryDark = Color(0xFFFFECC2)
val onPrimaryDark = Color(0xFF3E2E00)
val primaryContainerDark = Color(0xFFEDBD2B)
val onPrimaryContainerDark = Color(0xFF423200)
val secondaryDark = Color(0xFFDEC484)
val onSecondaryDark = Color(0xFF3E2E00)
val secondaryContainerDark = Color(0xFF4C3B07)
val onSecondaryContainerDark = Color(0xFFEACF8E)
val tertiaryDark = Color(0xFFD6FA7C)
val onTertiaryDark = Color(0xFF273500)
val tertiaryContainerDark = Color(0xFFADCF57)
val onTertiaryContainerDark = Color(0xFF2A3800)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF17130A)
val onBackgroundDark = Color(0xFFEBE1D2)
val surfaceDark = Color(0xFF17130A)
val onSurfaceDark = Color(0xFFEBE1D2)
val surfaceVariantDark = Color(0xFF4E4634)
val onSurfaceVariantDark = Color(0xFFD1C5AD)
val outlineDark = Color(0xFF9A907A)
val outlineVariantDark = Color(0xFF4E4634)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEBE1D2)
val inverseOnSurfaceDark = Color(0xFF353026)
val inversePrimaryDark = Color(0xFF755B00)
val surfaceDimDark = Color(0xFF17130A)
val surfaceBrightDark = Color(0xFF3E392E)
val surfaceContainerLowestDark = Color(0xFF110E06)
val surfaceContainerLowDark = Color(0xFF1F1B12)
val surfaceContainerDark = Color(0xFF231F16)
val surfaceContainerHighDark = Color(0xFF2E291F)
val surfaceContainerHighestDark = Color(0xFF39342A)
